import { Comment } from "@/types/entities/comment";
// consts/comments.ts
export const commentsData: Comment[] = [
    {
        "id": 1,
        "userId": 3,
        "name": "Belhadj",
        "surname": "Mohamed",
        "blogId": 1,
        "body": "Great insights! I really enjoyed this article.",
        "likes": 5,
        "isAReply": 0,
        "replies": 1,
        "originalCommentId": null,
        "createdAt": "2025-03-01T10:00:00Z",
        "updatedAt": "2025-03-01T10:15:00Z"
    },
    {
        "id": 2,
        "userId": 2,
        "name": "Younes",
        "surname": "Ahmed",
        "blogId": 1,
        "body": "I found the points very relevant to my work. Thanks for sharing!",
        "likes": 3,
        "isAReply": 0,
        "replies": 0,
        "originalCommentId": null,
        "createdAt": "2025-03-02T10:05:00Z",
        "updatedAt": "2025-03-01T10:10:00Z"
    },
    {
        "id": 3,
        "userId": 1,
        "name": "Karim",
        "surname": "Bensalem",
        "blogId": 1,
        "body": "This helped me understand the topic better. Well written!",
        "likes": 7,
        "isAReply": 0,
        "replies": 1,
        "originalCommentId": null,
        "createdAt": "2025-03-01T10:10:00Z",
        "updatedAt": "2025-03-01T10:20:00Z"
    },
    {
        "id": 4,
        "userId": 1,
        "name": "Belhadj",
        "surname": "Mohamed",
        "blogId": 2,
        "body": "I have a question about the second section. Can you clarify?",
        "likes": 2,
        "isAReply": 0,
        "replies": 13,
        "originalCommentId": null,
        "createdAt": "2025-03-01T10:15:00Z",
        "updatedAt": "2025-03-01T10:30:00Z"
    },
    {
        "id": 5,
        "userId": 2,
        "name": "Younes",
        "surname": "Ahmed",
        "blogId": 2,
        "body": "Loved this piece! I’d love to see more content like this.",
        "likes": 6,
        "isAReply": 0,
        "replies": 13,
        "originalCommentId": null,
        "createdAt": "2025-03-01T10:20:00Z",
        "updatedAt": "2025-03-01T10:25:00Z"
    },
    {
        "id": 6,
        "userId": 3,
        "name": "Karim",
        "surname": "Bensalem",
        "blogId": 2,
        "body": "Insightful and well-structured. Thanks for sharing!",
        "likes": 4,
        "isAReply": 0,
        "replies": 13,
        "originalCommentId": null,
        "createdAt": "2025-03-01T10:25:00Z",
        "updatedAt": "2025-03-01T10:35:00Z"
    },
    {
        "id": 7,
        "userId": 2,
        "name": "Younes",
        "surname": "Ahmed",
        "blogId": 1,
        "body": "I totally agree with your points!",
        "likes": 1,
        "isAReply": 1,
        "replies": 13,
        "originalCommentId": 1,
        "createdAt": "2025-03-01T10:30:00Z",
        "updatedAt": "2025-03-01T10:45:00Z"
    },
    {
        "id": 8,
        "userId": 3,
        "name": "Karim",
        "surname": "Bensalem",
        "blogId": 2,
        "body": "I appreciate the effort you put into this.",
        "likes": 2,
        "isAReply": 1,
        "replies": 13,
        "originalCommentId": 5,
        "createdAt": "2025-03-01T10:40:00Z",
        "updatedAt": "2025-03-01T10:50:00Z"
    },
    {
        "id": 9,
        "userId": 1,
        "name": "Belhadj",
        "surname": "Mohamed",
        "blogId": 1,
        "body": "That's an interesting perspective!",
        "likes": 0,
        "isAReply": 1,
        "replies": 13,
        "originalCommentId": 3,
        "createdAt": "2025-03-01T10:50:00Z",
        "updatedAt": "2025-03-01T10:55:00Z"
    },
    {
        "id": 10,
        "userId": 2,
        "name": "Younes",
        "surname": "Ahmed",
        "blogId": 2,
        "body": "Can you elaborate on your last point?",
        "likes": 3,
        "isAReply": 1,
        "replies": 13,
        "originalCommentId": 6,
        "createdAt": "2025-03-01T10:55:00Z",
        "updatedAt": "2025-03-01T11:00:00Z"
    }
];