export const paymentData: paimentEntity[] = [
    {
      id: 1,
      totalAmount: 50000,
      paidAmount: 50000,
      service_id: 1,
      service: {
        id: "101",
        image: "https://via.placeholder.com/150",
        title: "Website Development",
        body: "Full-stack website development with custom features.",
        price: 50000,
      },
      remainingBalance: 237000,
      paymentDate: 1698000000,
      status: "finished",
    },
    {
      id: 2,
      totalAmount: 30000,
      paidAmount: 15000,
      service_id: 2,
      service: {
        id: "102",
        image: "https://via.placeholder.com/150",
        title: "Graphic Design",
        body: "Logo and branding design package.",
        price: 30000,
      },
      remainingBalance: 237000,
      paymentDate: 1699000000,
      status: "unfinished",
    },
    {
      id: 3,
      totalAmount: 40000,
      paidAmount: 40000,
      service_id: 3,
      service: {
        id: "103",
        image: "https://via.placeholder.com/150",
        title: "SEO Optimization",
        body: "Comprehensive SEO services for website ranking.",
        price: 40000,
      },
      remainingBalance: 237000,
      paymentDate: 1697000000,
      status: "finished",
    },
    {
      id: 4,
      totalAmount: 20000,
      paidAmount: 10000,
      service_id: 4,
      service: {
        id: "104",
        image: "https://via.placeholder.com/150",
        title: "Social Media Management",
        body: "Managing social media campaigns for businesses.",
        price: 20000,
      },
      remainingBalance: 237000,
      paymentDate: 1696000000,
      status: "unfinished",
    },
    {
      id: 5,
      totalAmount: 60000,
      paidAmount: 60000,
      service_id: 5,
      service: {
        id: "105",
        image: "https://via.placeholder.com/150",
        title: "Mobile App Development",
        body: "Cross-platform mobile application development.",
        price: 60000,
      },
      remainingBalance: 237000,
      paymentDate: 1695000000,
      status: "finished",
    },
    {
      id: 6,
      totalAmount: 100000,
      paidAmount: 75000,
      service_id: 6,
      service: {
        id: "106",
        image: "https://via.placeholder.com/150",
        title: "E-commerce Platform",
        body: "Complete e-commerce platform with payment integrations.",
        price: 100000,
      },
      remainingBalance: 237000,
      paymentDate: 1694000000,
      status: "unfinished",
    },
    {
      id: 7,
      totalAmount: 25000,
      paidAmount: 25000,
      service_id: 7,
      service: {
        id: "107",
        image: "https://via.placeholder.com/150",
        title: "Video Production",
        body: "High-quality promotional video production.",
        price: 25000,
      },
      remainingBalance: 237000,
      paymentDate: 1693000000,
      status: "finished",
    },
    {
      id: 8,
      totalAmount: 45000,
      paidAmount: 45000,
      service_id: 8,
      service: {
        id: "108",
        image: "https://via.placeholder.com/150",
        title: "Content Writing",
        body: "Professional blog and article writing services.",
        price: 45000,
      },
      remainingBalance: 237000,
      paymentDate: 1692000000,
      status: "finished",
    },
    {
      id: 9,
      totalAmount: 70000,
      paidAmount: 50000,
      service_id: 9,
      service: {
        id: "109",
        image: "https://via.placeholder.com/150",
        title: "Digital Marketing",
        body: "Performance-based digital marketing services.",
        price: 70000,
      },
      remainingBalance: 237000,
      paymentDate: 1691000000,
      status: "unfinished",
    },
    {
      id: 10,
      totalAmount: 35000,
      paidAmount: 35000,
      service_id: 10,
      service: {
        id: "110",
        image: "https://via.placeholder.com/150",
        title: "Cloud Hosting",
        body: "Secure and scalable cloud hosting solutions.",
        price: 35000,
      },
      remainingBalance: 237000,
      paymentDate: 1690000000,
      status: "finished",
    },
    {
      id: 11,
      totalAmount: 15000,
      paidAmount: 10000,
      service_id: 11,
      service: {
        id: "111",
        image: "https://via.placeholder.com/150",
        title: "Technical Support",
        body: "24/7 technical support services.",
        price: 15000,
      },
      remainingBalance: 237000,
      paymentDate: 1689000000,
      status: "unfinished",
    },
    {
      id: 12,
      totalAmount: 80000,
      paidAmount: 80000,
      service_id: 12,
      service: {
        id: "112",
        image: "https://via.placeholder.com/150",
        title: "Custom CRM Development",
        body: "Tailored CRM solutions for businesses.",
        price: 80000,
      },
      remainingBalance: 237000,
      paymentDate: 1688000000,
      status: "finished",
    },
    {
      id: 13,
      totalAmount: 55000,
      paidAmount: 30000,
      service_id: 13,
      service: {
        id: "113",
        image: "https://via.placeholder.com/150",
        title: "Data Analysis",
        body: "Data-driven insights for business growth.",
        price: 55000,
      },
      remainingBalance: 237000,
      paymentDate: 1687000000,
      status: "unfinished",
    },
    {
      id: 14,
      totalAmount: 90000,
      paidAmount: 90000,
      service_id: 14,
      service: {
        id: "114",
        image: "https://via.placeholder.com/150",
        title: "Enterprise Software Development",
        body: "Custom enterprise-grade software solutions.",
        price: 90000,
      },
      remainingBalance: 237000,
      paymentDate: 1686000000,
      status: "finished",
    },
    {
      id: 15,
      totalAmount: 40000,
      paidAmount: 20000,
      service_id: 15,
      service: {
        id: "115",
        image: "https://via.placeholder.com/150",
        title: "IT Consulting",
        body: "Strategic IT consulting services.",
        price: 40000,
      },
      remainingBalance: 237000,
      paymentDate: 1685000000,
      status: "unfinished",
    },
  ];
  