const blogPosts: Blog[] = [
    {
        id: 1,
        title: "Opening Day of Boating Season, Seattle WA",
        author: "John Doe",
        content: "Of course the Puget Sound is very watery, and where there is water, there are boats. Today is  the Grand Opening of Boating Season when traffic gets stalled in the University District (UW) while the Montlake Bridge  lorem ipsum lorem ispum lorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum lorem lorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum lorem Of course the Puget Sound is very watery, and where there is water, there are boats. Today is  the Grand Opening of Boating Season when traffic gets stalled in the University District (UW) while the Montlake Bridge  lorem ipsum lorem ispum lorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum lorem lorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum lorem Of course the Puget Sound is very watery, and where there is water, there are boats. Today is  the Grand Opening of Boating Season when traffic gets stalled in the University District (UW) while the Montlake Bridge  lorem ipsum lorem ispum lorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum lorem lorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum lorem",
        likes: 250,
        date: new Date(),
        readingDuration: 240000, // milliseconds
        image: "/images/blog.png",
        category: "Droit administratif",
    },
    {
        id: 2,
        title: "Opening Day of Boating Season, Seattle WA",
        author: "John Doe",
        content: "Of course the Puget Sound is very watery, and where there is water, there are boats. Today is  the Grand Opening of Boating Season when traffic gets stalled in the University District (UW) while the Montlake Bridge  lorem ipsum lorem ispum lorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum lorem lorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum lorem Of course the Puget Sound is very watery, and where there is water, there are boats. Today is  the Grand Opening of Boating Season when traffic gets stalled in the University District (UW) while the Montlake Bridge  lorem ipsum lorem ispum lorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum lorem lorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum lorem Of course the Puget Sound is very watery, and where there is water, there are boats. Today is  the Grand Opening of Boating Season when traffic gets stalled in the University District (UW) while the Montlake Bridge  lorem ipsum lorem ispum lorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum lorem lorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum lorem",
        likes: 250,
        date: new Date(),
        readingDuration: 240000, // milliseconds
        image: "/images/blog.png",
        category: "Droit administratif",
    },
    {
        id: 3,
        title: "Opening Day of Boating Season, Seattle WA",
        author: "John Doe",
        content: "Of course the Puget Sound is very watery, and where there is water, there are boats. Today is  the Grand Opening of Boating Season when traffic gets stalled in the University District (UW) while the Montlake Bridge  lorem ipsum lorem ispum lorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum lorem lorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum lorem Of course the Puget Sound is very watery, and where there is water, there are boats. Today is  the Grand Opening of Boating Season when traffic gets stalled in the University District (UW) while the Montlake Bridge  lorem ipsum lorem ispum lorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum lorem lorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum lorem Of course the Puget Sound is very watery, and where there is water, there are boats. Today is  the Grand Opening of Boating Season when traffic gets stalled in the University District (UW) while the Montlake Bridge  lorem ipsum lorem ispum lorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum lorem lorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum lorem",
        likes: 250,
        date: new Date(),
        readingDuration: 240000, // milliseconds
        image: "/images/blog.png",
        category: "Droit administratif",
    },
    {
        id: 4,
        title: "Opening Day of Boating Season, Seattle WA",
        author: "John Doe",
        content: "Of course the Puget Sound is very watery, and where there is water, there are boats. Today is  the Grand Opening of Boating Season when traffic gets stalled in the University District (UW) while the Montlake Bridge  lorem ipsum lorem ispum lorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum lorem lorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum lorem Of course the Puget Sound is very watery, and where there is water, there are boats. Today is  the Grand Opening of Boating Season when traffic gets stalled in the University District (UW) while the Montlake Bridge  lorem ipsum lorem ispum lorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum lorem lorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum lorem Of course the Puget Sound is very watery, and where there is water, there are boats. Today is  the Grand Opening of Boating Season when traffic gets stalled in the University District (UW) while the Montlake Bridge  lorem ipsum lorem ispum lorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum lorem lorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum lorem",
        likes: 250,
        date: new Date(),
        readingDuration: 240000, // milliseconds
        image: "/images/blog.png",
        category: "Droit administratif",
    },
    {
        id: 5,
        title: "Opening Day of Boating Season, Seattle WA",
        author: "John Doe",
        content: "Of course the Puget Sound is very watery, and where there is water, there are boats. Today is  the Grand Opening of Boating Season when traffic gets stalled in the University District (UW) while the Montlake Bridge  lorem ipsum lorem ispum lorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum lorem lorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum lorem Of course the Puget Sound is very watery, and where there is water, there are boats. Today is  the Grand Opening of Boating Season when traffic gets stalled in the University District (UW) while the Montlake Bridge  lorem ipsum lorem ispum lorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum lorem lorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum lorem Of course the Puget Sound is very watery, and where there is water, there are boats. Today is  the Grand Opening of Boating Season when traffic gets stalled in the University District (UW) while the Montlake Bridge  lorem ipsum lorem ispum lorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum lorem lorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum lorem",
        likes: 250,
        date: new Date(),
        readingDuration: 240000, // milliseconds
        image: "/images/blog.png",
        category: "Droit administratif",
    },
    {
        id: 6,
        title: "Opening Day of Boating Season, Seattle WA",
        author: "John Doe",
        content: "Of course the Puget Sound is very watery, and where there is water, there are boats. Today is  the Grand Opening of Boating Season when traffic gets stalled in the University District (UW) while the Montlake Bridge  lorem ipsum lorem ispum lorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum lorem lorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum lorem Of course the Puget Sound is very watery, and where there is water, there are boats. Today is  the Grand Opening of Boating Season when traffic gets stalled in the University District (UW) while the Montlake Bridge  lorem ipsum lorem ispum lorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum lorem lorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum lorem Of course the Puget Sound is very watery, and where there is water, there are boats. Today is  the Grand Opening of Boating Season when traffic gets stalled in the University District (UW) while the Montlake Bridge  lorem ipsum lorem ispum lorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum lorem lorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum lorem",
        likes: 250,
        date: new Date(),
        readingDuration: 240000, // milliseconds
        image: "/images/blog.png",
        category: "Droit administratif",
    },
    {
        id: 7,
        title: "Opening Day of Boating Season, Seattle WA",
        author: "John Doe",
        content: "Of course the Puget Sound is very watery, and where there is water, there are boats. Today is  the Grand Opening of Boating Season when traffic gets stalled in the University District (UW) while the Montlake Bridge  lorem ipsum lorem ispum lorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum lorem lorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum lorem Of course the Puget Sound is very watery, and where there is water, there are boats. Today is  the Grand Opening of Boating Season when traffic gets stalled in the University District (UW) while the Montlake Bridge  lorem ipsum lorem ispum lorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum lorem lorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum lorem Of course the Puget Sound is very watery, and where there is water, there are boats. Today is  the Grand Opening of Boating Season when traffic gets stalled in the University District (UW) while the Montlake Bridge  lorem ipsum lorem ispum lorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum lorem lorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum lorem",
        likes: 250,
        date: new Date(),
        readingDuration: 240000, // milliseconds
        image: "/images/blog.png",
        category: "Droit administratif",
    },
    {
        id: 8,
        title: "Opening Day of Boating Season, Seattle WA",
        author: "John Doe",
        content: "Of course the Puget Sound is very watery, and where there is water, there are boats. Today is  the Grand Opening of Boating Season when traffic gets stalled in the University District (UW) while the Montlake Bridge  lorem ipsum lorem ispum lorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum lorem lorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum lorem Of course the Puget Sound is very watery, and where there is water, there are boats. Today is  the Grand Opening of Boating Season when traffic gets stalled in the University District (UW) while the Montlake Bridge  lorem ipsum lorem ispum lorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum lorem lorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum lorem Of course the Puget Sound is very watery, and where there is water, there are boats. Today is  the Grand Opening of Boating Season when traffic gets stalled in the University District (UW) while the Montlake Bridge  lorem ipsum lorem ispum lorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum lorem lorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum lorem",
        likes: 250,
        date: new Date(),
        readingDuration: 240000, // milliseconds
        image: "/images/blog.png",
        category: "Droit administratif",
    },
    {
        id: 9,
        title: "Opening Day of Boating Season, Seattle WA",
        author: "John Doe",
        content: "Of course the Puget Sound is very watery, and where there is water, there are boats. Today is  the Grand Opening of Boating Season when traffic gets stalled in the University District (UW) while the Montlake Bridge  lorem ipsum lorem ispum lorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum lorem lorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum lorem Of course the Puget Sound is very watery, and where there is water, there are boats. Today is  the Grand Opening of Boating Season when traffic gets stalled in the University District (UW) while the Montlake Bridge  lorem ipsum lorem ispum lorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum lorem lorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum lorem Of course the Puget Sound is very watery, and where there is water, there are boats. Today is  the Grand Opening of Boating Season when traffic gets stalled in the University District (UW) while the Montlake Bridge  lorem ipsum lorem ispum lorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum lorem lorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum lorem",
        likes: 250,
        date: new Date(),
        readingDuration: 240000, // milliseconds
        image: "/images/blog.png",
        category: "Droit administratif",
    },
    {
        id: 10,
        title: "Opening Day of Boating Season, Seattle WA",
        author: "Jane Smith",
        content: "Of course the Puget Sound is very watery, and where there is water, there are boats. Today is  the Grand Opening of Boating Season when traffic gets stalled in the University District (UW) while the Montlake Bridge  lorem ipsum lorem ispum lorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum lorem lorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum lorem Of course the Puget Sound is very watery, and where there is water, there are boats. Today is  the Grand Opening of Boating Season when traffic gets stalled in the University District (UW) while the Montlake Bridge  lorem ipsum lorem ispum lorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum lorem lorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum lorem Of course the Puget Sound is very watery, and where there is water, there are boats. Today is  the Grand Opening of Boating Season when traffic gets stalled in the University District (UW) while the Montlake Bridge  lorem ipsum lorem ispum lorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum lorem lorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum loremlorem lorem ipsum lorem ipsum lorem",
        likes: 300,
        date: new Date(),
        readingDuration: 4000,
        image: "/images/blog.png",
        category: "Droit des affaires",
    },
];

export default blogPosts;